import Config

config :njomber,
  nullifier_key:
    {[
       160,
       186,
       78,
       15,
       78,
       66,
       55,
       211,
       138,
       39,
       145,
       214,
       52,
       68,
       126,
       52,
       184,
       253,
       109,
       157,
       238,
       173,
       96,
       129,
       196,
       42,
       152,
       206,
       119,
       104,
       25,
       184
     ]},
  nullifier_key_commitment:
    {[
       150,
       203,
       151,
       84,
       31,
       248,
       20,
       165,
       176,
       37,
       48,
       160,
       244,
       190,
       254,
       141,
       186,
       109,
       91,
       81,
       172,
       140,
       174,
       156,
       223,
       195,
       53,
       45,
       6,
       150,
       30,
       91
     ]}

# Configure your database
config :njomber, Njomber.Repo,
  database: Path.expand("../njomber_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :njomber, NjomberWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "6xpYniUccv5F5vAuOMTRBuEkdnYhtdtzy79BVT63yyI3eGowrMv7YqJSVyUcKMxM",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:njomber, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:njomber, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :njomber, NjomberWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/njomber_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :njomber, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
